### ISSUE TITLE
base_jquery not found - 404

### ISSUE THREAD

**Issue by anderskristo** [Billmate/firecheckout#12]
base_jquery thats implemented in app/design/frontend/layout/billmateinvoice.xml is returned as 404 not found at https://efinance.se/billmate/base_jquery.js

Is this a modified version of jquery?

We did remove it from billmateinvoice.xml to get rid of the 404 error.

**Comment by andyjohansson** [comment]
Thanks @anderskristo for the contribution. @Boxedsolutions can you give an explanation?

**Comment by Boxedsolutions** [comment]
@andyjohansson fixed this

**Comment by andyjohansson** [comment]
This should be fixed now on server side.

**Comment by andyjohansson** [comment]
Can you verify @anderskristo?

**Comment by anderskristo** [comment]
@andyjohansson yes, working!
